### ISSUE TITLE
请问加上tpse后，合成的语音音质有提高吗？

### ISSUE THREAD

**Issue by Curry-AI** [cnlinxi/tpse_tacotron2#3]
作者你好，请问加上tpse后，合成的语音音质有提高吗？

**Comment by cnlinxi** [comment]
这个模型主要是应对情感丰富的语音合成场景，但是我仅仅有开源的标贝数据集去训练，所以训练完没有感觉什么变化。所以开源出来，希望有这类数据的人，能够提供反馈。

**Comment by joan126** [comment]
> 这个模型主要是应对情感丰富的语音合成场景，但是我仅仅有开源的标贝数据集去训练，所以训练完没有感觉什么变化。所以开源出来，希望有这类数据的人，能够提供反馈。

请问这里所谓的情感丰富的场景是指的喜怒哀乐或者惊讶这种emtion的合成吗？

**Comment by cnlinxi** [comment]
是的，最好文本能和语音对应上。比如，我今天考了100分!语气也应该很开心的感觉。



发自我的小米手机在 joan126 <notifications@github.com>，2020年9月26日 下午2:17写道：

这个模型主要是应对情感丰富的语音合成场景，但是我仅仅有开源的标贝数据集去训练，所以训练完没有感觉什么变化。所以开源出来，希望有这类数据的人，能够提供反馈。

请问这里所谓的情感丰富的场景是指的喜怒哀乐或者惊讶这种emtion的合成吗？

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cnlinxi/tpse_tacotron2/issues/3#issuecomment-699436790",
"url": "https://github.com/cnlinxi/tpse_tacotron2/issues/3#issuecomment-699436790",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
